import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // Auto-generated sidebars from docs
  installationAndSetupSidebar: [{ type: 'autogenerated', dirName: 'installation-and-setup' }],
  faqsSidebar: [{ type: 'autogenerated', dirName: 'faqs' }],
  guidesSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
};

export default sidebars;
