name: Test deployment

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-deploy:
    name: Test Docusaurus build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: website

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: website/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Test build website
        run: npm run build
